    header {
        background-color: #333;
        color: white;
        padding: 10px;
        text-align: center;
    }

    main {
        padding: 20px;
    }

    #mediaContainer {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
        grid-gap: 20px;
    }

    .media {
        position: relative;
        border-radius: 5px;
        overflow: hidden;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        max-width: 100%;
    }

    .media video,
    .media img {
        width: 100%;
        height: auto;
        max-height: 300px;
    }

    .commentsSection {
        background-color: rgba(255, 255, 255, 0.9);
        padding: 10px;
        box-sizing: border-box;
        display: none;
    }

    .commentsList {
        margin-top: 10px;
        max-height: 100px;
        overflow-y: auto;
    }

    .commentInput {
        width: calc(100% - 20px);
        margin-top: 5px;
    }

    .commentButton,
    .sendButton {
        width: calc(50% - 20px);
        margin-top: 5px;
        padding: 10px;
        background-color: #333;
        color: white;
        border: none;
        cursor: pointer;
    }

    .commentForm {
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    .commentForm textarea {
        flex: 1;
        margin-right: 10px;
    }

    .commentButton {
        margin-top: 10px;
        padding: 10px;
        background-color: #333;
        color: white;
        border: none;
        cursor: pointer;
    }
</style>
